### ISSUE TITLE
How to customise `play` with tokio lib ?

### ISSUE THREAD

**Issue by michael-dm** [NimonSour/interthread#6]
Hello again @NimonSour,

I'm trying to reproduce the edit_hack.rs example to customize `play`method but with tokio as lib.

It produces the following error : 
```
no variant or associated item named `play` found for enum `MyActorScript` in the current scope.
```

Here is the attribute macro : 
```rust
#[actor(lib = "tokio", channel = 2, file = "src/renderers.rs", edit(script(imp(play))))]
```

Do you have a clue of what might be happening ?
Thanks !

**Comment by michael-dm** [comment]
Ok I managed to make it work, I might have wrongly thought that the `play` part would be auto-added to the file.

```rust
pub struct RenderersActor {
    renderers: HashMap<RendererId, Renderer>,
}

#[interthread::actor(lib = "tokio", channel = 2, edit(script(imp(play))))]
impl RenderersActor {
    pub fn new() -> Self {
        let renderers = HashMap::new();
        Self { renderers }
    }
}

impl RenderersActorScript {
    pub async fn play(mut receiver: mpsc::Receiver<RenderersActorScript>, mut actor: RenderersActor) {
        while let std::option::Option::Some(msg) = receiver.recv().await {
            msg.direct(&mut actor).await;
        }
        eprintln!("RenderersActor the end ...");
    }
}
```

**Comment by NimonSour** [comment]
Hi Michael !
That's correct; using the `edit` keyword will prevent the `play` method 
from being included in the code generation process. 
If you wish to print on file the excluded code, you can achieve this by enclosing 
the specific section within the `file` argument inside the `edit` block like so:  
`#[actor(lib = "tokio", channel = 2, file = "src/renderers.rs", edit(script(imp( file(play)))))]`
Note the `file` argument inside the `edit`.
In fact if there is only one method all of the above should work:

`edit(script(imp( file(play)))))`
`edit(script( file(imp(play)))))`
`edit( file(script(imp(play)))))` 

The nesting of `file` arguments will result in error. 

In case you have more than one method and,
you need all of them to be printed on the file, use the following options :

`edit(script(imp( file(play),file(direct)))))`
`edit(script( file(imp(play, direct)))))`
`edit( file(script(imp(play, direct)))))` 

but if it's needed just one  of these two methods, there is only one option to achieve that:
 
`edit( script(imp(play, file(direct)))))` 

This will exclude `play` and print to file `direct` (ready to be edited).
I will explain.
Going back to your example, lets say after modifying the `play` method, 
there might be a need to make some changes to the `direct` method. 
In this scenario, the macro will need to exclude the `play` 
method from code generation (because you have it already) and, simultaneously, 
print the `direct` method to file. This can be achieved through the following syntax:

`#[actor(lib = "tokio", channel = 2, file = "src/renderers.rs", edit(script(imp( file(direct), play))))]`

Note that the macro will clean `file` arguments from edit block, adjusting itself to right state.
 
One special option is: 
`#[actor(lib = "tokio", channel = 2, file = "src/renderers.rs", edit(file)]`

in this case the macro will be replaced with generated code on file.

The documentation is minimal for this crate so keep asking questions your feedback is priceless, 
no I now what I have to improve in my docs.
I will add some examples as well.

**Comment by NimonSour** [comment]
My mistake, it used to be enough to declare the `file='path'`, 
but it proved to be difficult to work with. 
I've cleaned the typos in `examples`, and it looks like I have to 
add some information in the docs later.

Below is another attempt to explain the `file` and `edit` arguments; 
hopefully, it will help to understand it better and save a 
lot of time eventually.

The structure of the model from the `edit` point of view is:

```rust
script(
    def,       // <- script definition
    imp(..), // <- list of methods in impl block
    trt(..)    // <- list of traits
),

live(
    def,       // <- live definition
    imp(..), // <- list of methods in impl block
    trt(..)    // <- list of traits
)
```

Using the `edit` option is telling the macro:
   - Don't generate these parts of the model!


`edit( script )`   <- Excludes the whole Script enum 
`edit( live )`     <- Excludes the whole Live struct 
`edit( script(def) )`   <- Excludes Script enum definition
`edit( live(def) )`     <- Excludes Live struct definition
`edit( live(def,imp(new)) )`     <- Excludes Live struct definition and method "new"
`edit( script(imp(play)), live(imp(new)) )`   <- Excludes Script method "play" and Live method "new"

and so on...

Now, if one uses the `file` argument inside the `edit` block, this is telling the macro:

 1)  Don't generate these parts of the model!
 2)  Parts that are wrapped in `file` argument I want printed on the file (so I could modify them)!

Below, both `file` arguments point to Script definition:

a) `edit( file(script(def)) )`  
b) `edit( script(file(def)) )`  

Both will print on file Script definition and exclude it from generated code.

It's fine to use the `file` as in case "a", but if there is a mixture of 
Script parts that one wants [to just exclude] and [print on the file and exclude], 
there's no such flexibility anymore. Eventually, 
one ends up using the `file` as in case "b", something like:

```rust
edit( script( file(def), imp(play) ) )
```

which will print on file and exclude Script definition and just exclude the "play" method.

So, it does look like unreasonable flexibility to be able to point to 
the same thing in a few different ways but not when actually working 
with it. Often one is facing the situation that there is only 
one way to write what's desired.

`edit` is confusing due to its deep nested structure; using `file` 
adds even more confusion. But in some bad cases, it's possible 
to spread the argument on a few lines like so:

```rust
#[actor(lib = "tokio", channel = 2, file = "src/renderers.rs", 
       edit(
            script( imp(file(direct), play)),
            live,
           )
)]
```

It will work fine (will exclude the whole Live struct and Script::play, 
and will exclude and print on file Script::direct).

Importance:

Both `edit` and `file` give full control over generated code, a critical feature in some cases.

Let's say one wants an Actor that holds an ActorLive 
instance of itself. Without using `edit` argument, the definition for 
such an Actor will include an `Option<ActorLive>`:

```rust
struct Actor {
    live: Option<ActorLive>,
}

#[actor]
impl Actor {
    pub fn new() -> Self { Self { live: None } }

    pub fn set_live(&mut self, live: ActorLive) {
        self.live = Some(live);
    }
}
```

This means ActorLive has to forward alone of itself to the Actor:

```rust
fn main() {
    let mut act = ActorLive::new();
    act.set_live(act.clone());
}
```

Using `edit` argument, one can instantiate an Actor that can 
hold an instance of its ActorLive, instantly.

I've chosen this specific example for a reason. 
While I have your attention, it would be nice to make another 
important point that will definitely help:

A Live instance is just a `channel::Sender` plus the benefits of a `struct` type.

The definition of an ActorLive is usually:

```rust
struct ActorLive {
    sender: channel::Sender<Script>,
}
```

This means that an ActorLive instance can be instantiated before an Actor 
itself is instantiated... all it needs is a `channel::Sender` and voila, 
we have a new ActorLive before Actor itself.

```rust
struct Actor {
    live: ActorLive,
}

// We want method "new" of Live to be excluded from 
// code generation and to be printed on the file 
// so we could modify it 
// [interthread::actor(edit(live(imp( file(new) ))))]
// right after the desired part of code is added to
// the file our initial macro will change to 
[interthread::actor(edit(live(imp(new))))]

impl Actor {
    pub fn new(live: ActorLive) -> Self {
        Self { live }
    }
}

impl ActorLive {
    pub fn new() -> Self {
        let (sender, receiver) = std::sync::mpsc::channel();
        // Live instance is ready
        let actor_live = Self { sender };
        let actor = Actor::new(actor_live.clone());
        std::thread::spawn(move || { ActorScript::play(receiver, actor) });
        actor_live
    }
}
```

I've uploaded `self_live_actor.rs` in examples full of comments.

So while SDPL framework is helpful to work with code, 
when planning the Actor structure, remind yourself that SDPL is just a 
handy abstraction; `edit` and `file` arguments will help to stand above it.

**Comment by NimonSour** [comment]
Typos in `examples` are fixed, plus additional information in the docs concerning `file` and `edit` arguments, will be available with next release! Thanks, for your involvement !
